### ISSUE TITLE
Programatically opening row doesn't work

### ISSUE THREAD

**Issue by iuliuvisovan** [ProvataHealth/react-native-smooth-swipe-list#14]
What I have:

![image](https://user-images.githubusercontent.com/11357552/44666995-57982980-aa22-11e8-9a99-8ec30df978a9.png)
(the row has been opened by swiping)

What I'm trying to achieve: 
**Open row when pressing the icon on the right of each row (the three vertical dots icon)**

My code:

```
rowData = this.state.commands.map((x, i) => ({
        id: x.id + '',
        rowView: this.getRowView(x, i),
        rightSubView: this.getOptionsButton(x),
        style: styles.row
}))

getRowView(command, i) {
    return (
         <SwipeableCommand command={command} />
    );
}

render() {
     <SwipeList ref={x => this.swipeList = x} rowData={this.rowData} style={styles.listStyle} />
}
```

**SwipeableCommand.js:**

```
export default class SwipeableCommand extends Component {
    open = () => {
        //This doesn't work!
        this.row.open('right');
    }

    render() {
        return (
            <SwipeRow
                ref={x => this.row = x}
                startCloseTimeout={() => { }}
                clearCloseTimeout={() => { }}
            >
                <View style={styles.viewWrap}>
                   ...markup
                </View>
            </SwipeRow >
        )
    }
}

```

And whenever I press the '...' button the row just becomes frozen (the touchableopacity button doesnt even work anymore). I have looked inside the source code and couldn't figure out how to solve this, but I found out that `animateOpenOrClose(toValue, vx, noBounce) {` receives an `undefined` value for the `toValue` so it's going to try to animate the row towards `undefined`.

What am I missing/doing incorrectly?

**Comment by andrewgrewell** [comment]
The `SwipeRow` is a pretty complex component and most times you would use the `SwipeList` and let it handle setting up each row.
What you have above the `SwipeRow` being rendered in `SwipeableCommand` doesn't have enough information.
Here is an example how the `SwipeList` setting up a swipe row, which you would need to do something similar
```
renderSwipeListItem({ item, index }) {
        let ref = this.getRowRefProvider(item.id);
        return (
            <SwipeRow ref={ref}
                      id={item.id}
                      animateAdd={item.isNew}
                      leftSubView={item.leftSubView}
                      rightSubView={item.rightSubView}
                      leftSubViewOptions={item.leftSubViewOptions}
                      rightSubViewOptions={item.rightSubViewOptions}
                      gestureTensionParams={this.props.gestureTensionParams}
                      blockChildEventsWhenOpen={item.blockChildEventsWhenOpen}
                      isAnotherRowOpen={this.isAnotherRowOpen}
                      tryCloseOpenRow={this.tryCloseOpenRow}
                      style={[this.props.rowStyle, item.style]}
                      startCloseTimeout={this.onRowPressCheckSetCloseTimeout}
                      clearCloseTimeout={this.clearCloseTimeout}
                      onSwipeStart={this.handleSwipeStart}
                      onSwipeEnd={this.handleSwipeEnd}
                      onOpenStart={this.handleRowOpenStart}
                      onOpenEnd={this.handleRowOpenEnd}
                      onCloseStart={this.handleRowCloseStart}
                      onCloseEnd={this.handleRowCloseEnd}
                      {...this.props.swipeRowProps}
                      {...item.props}>
                {item.rowView}
            </SwipeRow>
        );
    },
```
In particular the row needs to know about the content it is rendering.

That said it looks like the `open` method was broken anyway. I have updated the code. You will want to call `this.props.openRow` inside your `SwipeableCommand`

**Comment by andrewgrewell** [comment]
I've also updated the README since it wasn't clear that the `SwipeList` wrapped the `rowView` and `left/rightSubView` in a `SwipeRow`

**Comment by iuliuvisovan** [comment]
Hey, appreciate you being so active with the maintenance. I'll give it a shot again tomorrow and let you know. Thanks!

EDIT: `this.props.openRow()` does the trick!
