### ISSUE TITLE
How to apply styles to left/right subview?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [ProvataHealth/react-native-smooth-swipe-list#3]
I couldn't find any place to put my style on left/right subview, any ideas?

**Comment by andrewgrewell** [comment]
The way I usually do it is by placing the style on the sub view that I am passing in as row data (e.g. `leftSubView: <View style={{ backgroundColor: 'blue' }} />`).

for example if your render method looked like this:
```
render() {
    return <SwipeList rowData={this.rowData} />;
}
```
and `this.rowData` looked like this:
```
{
   id: rowId,
   rowView: <YourRowViewComponent/>,
   leftSubView: <YourLeftSubViewComponent style={styles.leftSubView} />
{
```
your left sub view would be styled like any other component.

Is that helpful? If not let me know your use case and I'll see if I have a better answer.

**Comment by Doko-Demo-Doa** [comment]
Thank you very much. It's simpler than I thought (I was looking for a built-in props but your solution is way better).
