### ISSUE TITLE
Update to use FlatList

### ISSUE THREAD

**Issue by wswoodruff** [ProvataHealth/react-native-smooth-swipe-list#4]
Yo! Are there plans to update this to use react-native's more performant [FlatList](https://facebook.github.io/react-native/docs/flatlist.html)?
It's faster, you no longer need to manage a dataSource, the api is much simpler!

**Comment by andrewgrewell** [comment]
Sorry, not in the near future. It doesn't look like it would take much work though, if you would like to submit a PR we could get it in there.

**Comment by wswoodruff** [comment]
Ok I might give it a shot!

**Comment by Suresh-R-S** [comment]
Any update on this ?

**Comment by andrewgrewell** [comment]
Not as far as I know. If you wanted to give it a shot I am available to answer any questions. 
I don't currently have the time to implement it, and we haven't noticed any performance issues with the current `ScrollView` / `ListView` options.

**Comment by wswoodruff** [comment]
Hey @Suresh-R-S Sorry I haven't had time yet to work on this update either

**Comment by andrewgrewell** [comment]
This will been merged in #13 
look for `react-native-smooth-swipe-list`@`1.4.0`+
