### ISSUE TITLE
Can you provide renderHeader function?

### ISSUE THREAD

**Issue by hyochan35** [ProvataHealth/react-native-smooth-swipe-list#6]
Can you provide renderHeader function like provided in link below?

http://shoutem.github.io/docs/ui-toolkit/components/list-view

**Comment by andrewgrewell** [comment]
The swipe list extends `ListView` (or `ScrollView` if you pass `isScrollView`).
so you can pass any props the `ListView` takes.
See the [React Native ListView api](https://facebook.github.io/react-native/docs/listview.html)
e.g. 
```
<SwipeList renderHeader={this.renderMyHeader} ... />
```

**Comment by hyochan35** [comment]
Thank You!
