### ISSUE TITLE
Remove particular row

### ISSUE THREAD

**Issue by wswoodruff** [ProvataHealth/react-native-smooth-swipe-list#7]
I'm having trouble removing a particular row and having that one animate while the others stay put.

What am I doing wrong here?:

![swipe-list-demo](https://user-images.githubusercontent.com/9013245/27512672-f6feb1f0-5916-11e7-8770-c266d52f3517.gif)

**Comment by andrewgrewell** [comment]
Hmm, not sure without seeing the code, but are you assigning a unique id to each `rowData` item?
e.g.
```
<SwipeList rowData={[
    { id: 'guacamole' ... }, { id: 'pico de gallo' ... }, { id: 'chorizo bean dip' ...}
]} />
```

**Comment by wswoodruff** [comment]
Ohh, I was setting the `id` to whatever `i` was in my loop. Soon as I set it to Math.random() it worked. Any suggestions for a better pattern than Math.random() if I want completely arbitrary keys? The title would work, but what about a list with multiple guacamoles?

**Comment by andrewgrewell** [comment]
I usually just use something I know will be unique, in this case I would use the item title.
The `SwipeList` will also assign a rowId starting at 1, so if you don't care to be able to reference the rows you can let the list handle it

**Comment by wswoodruff** [comment]
`id` is required by SwipeList rowData, it throws a warning if I leave `id` out

**Comment by andrewgrewell** [comment]
Ok, I'll look into updating that prop warning
